# Generated by Django 3.2 on 2023-02-21 04:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='contour',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
